services:
  - type: web
    name: gramaarogya-web
    runtime: node
    plan: free
    autoDeploy: true
    buildCommand: npm ci; npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production

  - type: web
    name: gramaarogya-api
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: python backend.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
